### PR TITLE
Optimize TEvVPut/TEvVGet message serialization

### PR DESCRIPTION
**Pull request by kirillgrachoff**
I hereby agree to the terms of the CLA available at: [link](https://yandex.ru/legal/cla/?lang=ru).

PR for [Issue](https://github.com/ydb-platform/ydb/wiki/Student-Projects#optimize-tevvputtevvget-message-serialization)

### CODE REVIEW

**Comment by kirillgrachoff** [comment]
Кажется, что-то пошло не так...
```
----------- Put_32 ---------------
 samples:       6469
 iterations:    25837266
 iterations hr:    25.8M
 run time:      5.00156987
 per iteration: 359.517217 cycles
----------- Put_64 ---------------
 samples:       6597
 iterations:    26868115
 iterations hr:    26.9M
 run time:      5.00125328
 per iteration: 352.0910991 cycles
----------- Put_128 ---------------
 samples:       6512
 iterations:    26183466
 iterations hr:    26.2M
 run time:      5.000829399
 per iteration: 359.2299092 cycles
----------- Put_256 ---------------
 samples:       6516
 iterations:    26212420
 iterations hr:    26.2M
 run time:      5.001141795
 per iteration: 353.6332096 cycles
 ```

**Comment by kirillgrachoff** [comment]
`~23000 events over 1000ms`

```
Send 226600 Ack 226599 over 10000ms
Send 228755 Ack 228755 over 10000ms
Send 235353 Ack 235353 over 10000ms
Send 215026 Ack 215026 over 10000ms
Send 219348 Ack 219348 over 10000ms
Send 233714 Ack 233714 over 10000ms
Send 234652 Ack 234652 over 10000ms
Send 234838 Ack 234838 over 10000ms
Send 241275 Ack 241275 over 10000ms
Send 241329 Ack 241329 over 10000ms
Send 252314 Ack 252314 over 10000ms
Send 239803 Ack 239803 over 10000ms
Send 232070 Ack 232070 over 10000ms
Send 234854 Ack 234854 over 10000ms
Send 231226 Ack 231226 over 10000ms
Send 241138 Ack 241138 over 10000ms
Send 228481 Ack 228481 over 10000ms
```

**Comment by kirillgrachoff** [comment]
```
----------- Put_32 ---------------
 samples:       2245
 iterations:    3113760
 iterations hr:    3.11M
 run time:      5.002619823
 per iteration: 2846.953931 cycles
----------- Put_64 ---------------
 samples:       2295
 iterations:    3252525
 iterations hr:    3.25M
 run time:      5.001846492
 per iteration: 2870.882431 cycles
----------- Put_128 ---------------
 samples:       2260
 iterations:    3156328
 iterations hr:    3.16M
 run time:      5.002874157
 per iteration: 2999.205924 cycles
----------- Put_256 ---------------
 samples:       2307
 iterations:    3288330
 iterations hr:    3.29M
 run time:      5.001070248
 per iteration: 2953.179791 cycles
----------- Get ---------------
 samples:       5679
 iterations:    19911205
 iterations hr:    19.9M
 run time:      5.08152779
 per iteration: 443.4533697 cycles
 ```

**Comment by kirillgrachoff** [comment]
```
110100480 BytesWritten
860160 EvCount
0.366612s SerializeDuration
0.253605s DeserializeDuration

0.6917531341 (Speed serialize) / (Speed deserialize)

2350 Ev/ms write
300820 B/ms write
3399 Ev/ms read
435179 B/ms read

850 cycles/Ev write
6 cycles/B write
588 cycles/Ev read
4 cycles/B read
```

**Comment by kirillgrachoff** [comment]
```
1997537280 BytesWritten
15605760 EvCount
7.470839s SerializeDuration
5.908116s DeserializeDuration

0.7908236277 (Speed serialize) / (Speed deserialize)

2089 Ev/ms write
267407 B/ms write
2641 Ev/ms read
338107 B/ms read

955 cycles/Ev write
7 cycles/B write
755 cycles/Ev read
5 cycles/B read
```

**Comment by kirillgrachoff** [comment]
New:
```
Send 24093 Ack 24092 over 999ms
Send 25717 Ack 25717 over 1000ms
Send 24896 Ack 24896 over 1000ms
Send 24254 Ack 24254 over 1000ms
Send 25222 Ack 25222 over 1000ms
Send 24268 Ack 24268 over 1000ms
Send 24176 Ack 24176 over 1000ms
Send 23409 Ack 23409 over 1000ms
Send 23099 Ack 23099 over 1000ms
Send 23993 Ack 23993 over 1000ms
Send 23728 Ack 23728 over 1000ms
```
Old:
```
Send 23775 Ack 23774 over 1000ms
Send 24595 Ack 24595 over 1000ms
Send 24471 Ack 24471 over 1000ms
Send 24417 Ack 24417 over 1000ms
Send 19962 Ack 19962 over 1000ms
Send 22462 Ack 22462 over 1000ms
Send 25391 Ack 25391 over 1000ms
Send 26392 Ack 26392 over 1000ms
Send 23354 Ack 23354 over 1000ms
Send 24890 Ack 24890 over 1000ms
Send 26537 Ack 26537 over 1000ms
```

**Comment by kirillgrachoff** [comment]
New:
```
1997537280 BytesWritten
15605760 EvCount
8.754983s SerializeDuration
9.428257s DeserializeDuration

1.076901806 (Speed serialize) / (Speed deserialize)

1782 Ev/ms write
228185 B/ms write
1655 Ev/ms read
211872 B/ms read

1119 cycles/Ev write
8 cycles/B write
1205 cycles/Ev read
9 cycles/B read
```
Old:
```
1997537280 BytesWritten
15605760 EvCount
6.621464s SerializeDuration
5.010689s DeserializeDuration

0.7567343113 (Speed serialize) / (Speed deserialize)

2357 Ev/ms write
301697 B/ms write
3114 Ev/ms read
398710 B/ms read

846 cycles/Ev write
6 cycles/B write
640 cycles/Ev read
5 cycles/B read

**Comment by kirillgrachoff** [comment]
New:
```
2559344640 BytesWritten
15605760 EvCount
9.106681s SerializeDuration
9.781585s DeserializeDuration

1.074110864 (Speed serialize) / (Speed deserialize)

1713 Ev/ms write
281061 B/ms write
1595 Ev/ms read
261664 B/ms read

1164 cycles/Ev write
7 cycles/B write
1250 cycles/Ev read
7 cycles/B read
```
Old:
```
2559344640 BytesWritten
15605760 EvCount
6.815951s SerializeDuration
5.462496s DeserializeDuration

0.8014282967 (Speed serialize) / (Speed deserialize)

2289 Ev/ms write
375545 B/ms write
2857 Ev/ms read
468572 B/ms read

871 cycles/Ev write
5 cycles/B write
698 cycles/Ev read
4 cycles/B read
```

**Comment by kirillgrachoff** [comment]
Old:
```
Send 21030 Ack 21029 over 1000ms
Send 22441 Ack 22441 over 1000ms
Send 20219 Ack 20219 over 1000ms
Send 22666 Ack 22666 over 1000ms
Send 22877 Ack 22877 over 1000ms
Send 21353 Ack 21353 over 1000ms
Send 20756 Ack 20756 over 1000ms
Send 19361 Ack 19361 over 1000ms
Send 19781 Ack 19781 over 1000ms
Send 21539 Ack 21539 over 1000ms
Send 22930 Ack 22930 over 1000ms
```
New:
```
Send 24688 Ack 24687 over 999ms
Send 26637 Ack 26637 over 1000ms
Send 24044 Ack 24044 over 1000ms
Send 23040 Ack 23040 over 1000ms
Send 23481 Ack 23481 over 1000ms
Send 19961 Ack 19961 over 1000ms
Send 19778 Ack 19778 over 1000ms
Send 20757 Ack 20757 over 1000ms
Send 21152 Ack 21152 over 1000ms
Send 21572 Ack 21572 over 1000ms
```

**Comment by kirillgrachoff** [comment]
Actors local bench

New:
```
Send 387219 Ack 387218 over 1000ms
Send 383595 Ack 383595 over 1000ms
Send 375622 Ack 375622 over 1000ms
Send 375928 Ack 375928 over 1000ms
Send 385025 Ack 385025 over 1000ms
Send 382973 Ack 382973 over 1000ms
Send 405243 Ack 405243 over 1000ms
Send 401707 Ack 401707 over 1000ms
Send 399250 Ack 399250 over 1000ms
Send 419108 Ack 419108 over 1000ms
Speed: 391567 Ev/s
```
Old:
```
Send 369251 Ack 369250 over 1000ms
Send 305827 Ack 305827 over 1000ms
Send 294563 Ack 294563 over 1000ms
Send 402019 Ack 402019 over 1000ms
Send 367661 Ack 367661 over 1000ms
Send 357071 Ack 357071 over 1000ms
Send 418796 Ack 418796 over 1000ms
Send 358630 Ack 358630 over 1000ms
Send 348517 Ack 348517 over 1000ms
Send 253161 Ack 253161 over 1000ms
Send 373256 Ack 373256 over 1000ms
Send 241616 Ack 241616 over 1000ms
Send 329506 Ack 329506 over 1000ms
Send 321464 Ack 321464 over 1000ms
Send 383330 Ack 383330 over 1000ms
Send 337542 Ack 337542 over 1000ms
Send 199466 Ack 199466 over 1000ms
Speed: 333039 Ev/s
```

**Comment by kirillgrachoff** [comment]
Actors remote bench
Old:
```
Send 28057 Ack 28056 over 1000ms
Send 25132 Ack 25132 over 1000ms
Send 29648 Ack 29648 over 1000ms
Send 28980 Ack 28980 over 1000ms
Send 29763 Ack 29763 over 1000ms
Send 29651 Ack 29651 over 1000ms
Send 29329 Ack 29329 over 1000ms
Send 28385 Ack 28385 over 1000ms
Send 29424 Ack 29424 over 1000ms
Send 30128 Ack 30128 over 1000ms
Send 30447 Ack 30447 over 1000ms
Send 28837 Ack 28837 over 1000ms
Send 27133 Ack 27133 over 1000ms
Send 27670 Ack 27670 over 1000ms
Send 28927 Ack 28927 over 1000ms
Speed: 28767 Ev/s
```
New:
```
Send 28647 Ack 28646 over 1000ms
Send 28208 Ack 28208 over 1000ms
Send 26493 Ack 26493 over 1000ms
Send 24981 Ack 24981 over 1000ms
Send 24920 Ack 24920 over 1000ms
Send 24972 Ack 24972 over 1000ms
Send 23161 Ack 23161 over 1000ms
Send 24541 Ack 24541 over 1000ms
Send 23292 Ack 23292 over 1000ms
Send 24863 Ack 24863 over 1000ms
Send 24979 Ack 24979 over 1000ms
Send 26252 Ack 26252 over 1000ms
Send 25039 Ack 25039 over 1000ms
Send 25845 Ack 25845 over 1000ms
Send 25921 Ack 25921 over 1000ms
Send 24616 Ack 24616 over 1000ms
Send 27514 Ack 27514 over 1000ms
Send 24168 Ack 24168 over 1000ms
Send 26607 Ack 26607 over 1000ms
Send 27683 Ack 27683 over 1000ms
Send 23372 Ack 23372 over 1000ms
Send 23165 Ack 23165 over 1000ms
Send 23231 Ack 23231 over 1000ms
Send 21808 Ack 21808 over 1000ms
Send 22209 Ack 22209 over 1000ms
Send 21382 Ack 21382 over 1000ms
Send 21799 Ack 21799 over 1000ms
Speed: 24802 Ev/s
```

**Comment by kirillgrachoff** [comment]
Actors remote bench

Old:
`Speed: 29693 Ev/s; 0.03369217281 ms/Ev`
New:
`Speed: 28880 Ev/s; 0.03464057728 ms/Ev`

**Comment by kirillgrachoff** [comment]
Proto bench
```
TEvVPut2
1031798784 BytesWritten
6291456 EvCount
2.740890s SerializeDuration
3.439492s DeserializeDuration

1.254881444 (Speed serialize) / (Speed deserialize)

2296 Ev/ms write
376568 B/ms write
1829 Ev/ms read
300028 B/ms read

869 cycles/Ev write
5 cycles/B write
1090 cycles/Ev read
6 cycles/B read

TEvVPut
1031798784 BytesWritten
6291456 EvCount
2.313911s SerializeDuration
2.365979s DeserializeDuration

1.022502162 (Speed serialize) / (Speed deserialize)

2720 Ev/ms write
446086 B/ms write
2660 Ev/ms read
436278 B/ms read

733 cycles/Ev write
4 cycles/B write
750 cycles/Ev read
4 cycles/B read
```

**Comment by maximyurchuk** [comment]
This PR has been in draft for over a year. If the PR is still relevant, please reopen it.

**Pull request closed without merging**
