### PR TITLE
Migrating from antlr3 to antlr4

### PR DESCRIPTION
**Pull request by OrlovPavel**
### Changelog entry 

...

### Changelog category 

* Experimental feature
* Improvement

### Additional information

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

### CODE REVIEW

**Comment by dcherednik** [comment]
Can you please set draft status for this pr?

**Comment by OrlovPavel** [comment]
Currently, antlr4 can't generate protobuf. Here are all available targets - https://github.com/antlr/antlr4/blob/master/doc/targets.md 
But I am going to try adding protobuf target according to this instruction https://github.com/tunnelvisionlabs/antlr4/blob/master/doc/creating-a-language-target.md using your custom protobuf.stg. Unfortunately this means changing antlr4 source code and then rebuilding jar, but antlr3 in ydb was once changed the same way to generate protobuf.

**Comment by dcherednik** [comment]
antlr3 hasn't been not patched. Moreover in case of cmake build find_library will try to use antlr3 from system. 
antlr3 uses custom stg file ydb/library/yql/parser/proto_ast/org/antlr/codegen/templates/protobuf/protobuf.stg.in

So the primary task is to find the way to do something similar for antlr4. 

> Currently, antlr4 can't generate protobuf. Here are all available targets - https://github.com/antlr/antlr4/blob/master/doc/targets.md But I am going to try adding protobuf target according to this instruction https://github.com/tunnelvisionlabs/antlr4/blob/master/doc/creating-a-language-target.md using your custom protobuf.stg. Unfortunately this means changing antlr4 source code and then rebuilding jar, but, as I know, antlr3 in ydb was once changed the same way to generate protobuf.

**Comment by dcherednik** [comment]
I will close the pr. Please make the new one if found the way to use antlr4 to generate protobuf.

**Pull request closed without merging**
